# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main  # Defina a branch que aciona o pipeline (pode ser ajustada conforme necessário)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '11'  # Especifique a versão do Java que você deseja usar

- script: 'mvn clean install'  # Comando para construir o projeto e executar os testes
  displayName: 'Construir e executar testes'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'Execução de Testes'  # Título para a execução dos testes
  displayName: 'Publicar resultados dos testes'
