trigger:
- main # Define aqui o nome da branch que aciona a pipeline (pode ser 'main', 'master', ou outra de sua escolha)

pool:
  vmImage: 'ubuntu-latest' # Escolha a imagem da máquina virtual apropriada para o ambiente de build

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:

  - script: |
      # Instalação do Maven
      wget -q https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
      tar zxvf apache-maven-3.8.4-bin.tar.gz
      export PATH=$(pwd)/apache-maven-3.8.4/bin:$PATH
    displayName: 'Instalar o Maven'

  - script: 'mvn clean test' # Comando para construir e testar o projeto com Maven
    displayName: 'Executar Testes'

  - script: 'mvn surefire-report:report' # Comando para gerar relatórios de testes com Surefire
    displayName: 'Gerar Relatório de Testes'

  - script: 'mvn jacoco:report' # Comando para gerar relatórios de cobertura de código com JaCoCo
    displayName: 'Gerar Relatório de Cobertura de Código'
